### ISSUE TITLE
reversion.VersionAdmin in admin

### ISSUE THREAD

**Issue by mazing** [edoburu/django-polymorphic-tree#27]
It is not possible to combine `PolymorphicMPTTParentModelAdmin` and `reversion.VersionAdmin` in the admin. Depending on the order of `PolymorphicMPTTParentModelAdmin` and `VersionAdmin` each of them are not recognized.

**Comment by bashu** [comment]
@vdboor how hard do you think this one?

**Comment by vdboor** [comment]
I've just implemented this in a project, and fixed some bits along the way.
You can try the new release, 1.2.1 (+ django-polymorphic 0.9.1) which have better support for reversion display; they didn't properly redirect the history and reversion views to the child admin.

The template are also updated, so breadcrumbs display properly.
However, note you may want to override a `admin/polymorphic_tree/object_history.html` template, so it extends the `reversion/object_history.html` template instead of the default admin. See for example:

```
{% extends 'reversion-compare/object_history.html' %}{# redirect to the proper django-reversion-compare base template #}

{% block breadcrumbs %}{% if not is_popup %}{% include "admin/polymorphic_tree/object_history_breadcrumbs.html" %}{% endif %}{% endblock %}
```
